### PR TITLE
Fix the subuid & subgid user detection and addition.

### PR DESCRIPTION
**Pull request by romainsc**
Hi,

The subgid and subuid check part was not working on my setup (a vanilla RHEL 8 server).

I found [a different way to check line presence](https://stackoverflow.com/questions/30786263/only-check-whether-a-line-present-in-a-file-ansible) and after some tests it works.

Perhaps this way will improve further usage.

### CODE REVIEW

**Review by ikke-t — COMMENTED** [review]
Hmmm, I trust it works of you say so, but odd that lineinfile docs don't mention such return code ".found". Where does that come from? Doc is here: https://docs.ansible.com/ansible/latest/modules/lineinfile_module.html

**Comment by romainsc** [comment]
Hi @ikke-t ,

I found this solution in multiple Stackoverflow pages, ie:

- https://stackoverflow.com/a/30788277
- https://stackoverflow.com/a/62609075

But your remark triggered additional research in order to have a solution that is fully officially documented, and I found that the [find module](https://docs.ansible.com/ansible/latest/modules/find_module.html) would do the job in a cleaner way.

Do you prefer I request another pull with an implementation based on this?

Best Regards,

**Comment by ikke-t** [comment]
That was really good find (happy to include the pun)! Looks cleaner and made for the purpose. Please do, test and rebase dropping the earlier trials.

**Comment by romainsc** [comment]
Hi @ikke-t , job done.

**Pull request merged**
